### ISSUE TITLE
Build image with book/environment.yml

### ISSUE THREAD

**Issue by jmunroe** [ScienceCore/climaterisk#39]
We need our 2i2c hub to always be using the book/environment.yml for both development and learning

### Tasks
- [x] Create GitHub actions or otherwise to build a new image when environment.yml is changed
- [x] Add nbgitpuller to image
- [x] Add jupyterlab_myst to image
- [x] Test the image with existing book examples
- [ ] Configure both https://showcase.2i2c.cloud and https://sciencecore.opensci.2i2c.cloud as hubs where this content can be explored interactively
