### ISSUE TITLE
Initialise translation workflow with Crowdin

### ISSUE THREAD

**Issue by jnywong** [ScienceCore/climaterisk#88]
### Context

Content for the ScienceCore TOPST course will be finalised Sep 16. One of the deliverables is to translate the content into Spanish.

The content to be localised: https://github.com/ScienceCore/climaterisk/

We will use the Crowdin platform for the initial translations and the content will be proofread by MetaDocencia.

March 2025 is a rough date for delivery.

### Tasks
- [x] Create a new template repository to enable localisation workflow 👉 https://github.com/ScienceCore/climaterisk-es
- [x] Set up Crowdin project 👉 https://crowdin.com/project/sciencecore
- [x] Invite collaborators to the Crowdin project
- [x] Walk @dhavide through the workflow
